#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new SellerCenter\SDK\Console\VersionCommand());
$application->add(new SellerCenter\SDK\Console\UpdateSerializedFixturesFromXmlCommand());
$application->run();
