#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use SellerCenter\SDK\Console\VersionCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new VersionCommand());
$application->run();